"""New Migration2

Revision ID: 639567717bd0
Revises: 9cead3cdd861
Create Date: 2022-10-20 15:59:48.211853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '639567717bd0'
down_revision = '9cead3cdd861'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
