version: '3'
services:
  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data/
    env_file:
      - ./.env

  redis:
    container_name: redis
    image: redis
    volumes:
      - ../data/redis:/data
    restart: always

  api_service:
      build: 
        context: ../fastapi-solution/
        dockerfile: Dockerfile
      depends_on:
        - redis
        - postgres
      env_file:
        - ./.env
      restart: always

  nginx:
    image: nginx:1.21.3-alpine

    ports:
      - "96:96"

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - api_service

volumes:
  pgdata: